clear all
close all
clc

syms t u(t) real
syms umin umax alpha real
l=(umax-umin)/2;
umid=(umax+umin)/2;
Ttotal=(l^2)/2;
mu=1;

gamma=((u-umin)^2)/(l^2);
delta=0;
ro=0;
sigma=0;
y1=subs(simplify(...
    -Ttotal*abs(mu)*(gamma-(1-gamma))...
    -Ttotal*abs(mu)*(delta-(1-delta))...
    +Ttotal*abs(mu)*(ro-(1-ro))...
    +Ttotal*abs(mu)*(sigma-(1-sigma))),...
    [umin,umax],[-alpha,alpha])
    
gamma=1;
delta=1-(l-(u-umid))^2/(l^2);
ro=(u-umid)^2/(l^2);
sigma=(u-umid)^2/(l^2);
y2=subs(simplify(...
    -Ttotal*abs(mu)*(gamma-(1-gamma))...
    -Ttotal*abs(mu)*(delta-(1-delta))...
    +Ttotal*abs(mu)*(ro-(1-ro))...
    +Ttotal*abs(mu)*(sigma-(1-sigma))),...
    [umin,umax],[-alpha,alpha])

 gamma=1;
 delta=1;
 ro=1;
 sigma=1-(umax-u)^2/(l^2);
 y3=subs(simplify(...
    -Ttotal*abs(mu)*(gamma-(1-gamma))...
    -Ttotal*abs(mu)*(delta-(1-delta))...
    +Ttotal*abs(mu)*(ro-(1-ro))...
    +Ttotal*abs(mu)*(sigma-(1-sigma))),...
    [umin,umax],[-alpha,alpha])

gamma=1-(umid-u)^2/(l^2);
delta=1-(umid-u)^2/(l^2);
ro=(l-(umid-u))^2/(l^2);
sigma=0;
y4=subs(simplify(...
    -Ttotal*abs(mu)*(gamma-(1-gamma))...
    -Ttotal*abs(mu)*(delta-(1-delta))...
    +Ttotal*abs(mu)*(ro-(1-ro))...
    +Ttotal*abs(mu)*(sigma-(1-sigma))),...
    [umin,umax],[-alpha,alpha])

d1=simplify(u*diff(y1,t)-y1*diff(u,t))
d2=simplify(u*diff(y2,t)-y2*diff(u,t))
d3=simplify(u*diff(y3,t)-y3*diff(u,t))
d4=simplify(u*diff(y4,t)-y4*diff(u,t))

i1=simplify(int(d1,t))
i2=simplify(int(d2,t))
i3=simplify(int(d3,t))
i4=simplify(int(d4,t))
